import { EVOLUTION_TABLE, TIER_LEVELS } from "../src/lib/evolution";
import { DEFAULT_CONFIG, type GameConfig } from "../src/lib/game-config";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const APP_URL = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";
const API_STATS_URL = `${APP_URL}/api/stats`;

interface GameStats {
  config: GameConfig;
  metrics: {
    totalUsers: number;
    activeToday: number;
    avgLevel: number;
    todayFeeds: number;
    totalComments: number;
    engagementRate: number;
    balanceScore: number;
  };
  evolutionDistribution: Record<string, number>;
  recommendations: string[];
}

interface BalancePatch {
  patch: Partial<GameConfig>;
  reason: string;
  expectedEffect: string;
}

async function fetchStats(): Promise<GameStats | null> {
  try {
    const res = await fetch(API_STATS_URL);
    if (!res.ok) {
      console.error(`Stats API returned ${res.status}`);
      return null;
    }
    return res.json();
  } catch (err) {
    console.error("Failed to fetch stats:", err);
    return null;
  }
}

function analyzeBalance(stats: GameStats): BalancePatch[] {
  const patches: BalancePatch[] = [];
  const config = stats.config;
  const m = stats.metrics;

  // Rule 1: Low engagement → increase reward
  if (m.engagementRate < 15 && m.totalUsers > 5) {
    const newExp = config.expPerFeed + 2;
    patches.push({
      patch: { expPerFeed: newExp },
      reason: `참여율 ${m.engagementRate}%로 낮음 (기준 15%)`,
      expectedEffect: `먹이당 EXP ${config.expPerFeed} → ${newExp}로 증가. 참여율 상승 기대.`,
    });
  }

  // Rule 2: Too fast progression → slow down
  if (m.avgLevel > 35 && m.totalUsers > 5) {
    patches.push({
      patch: { expThresholdMultiplier: config.expThresholdMultiplier + 0.15 },
      reason: `평균 레벨 ${m.avgLevel}로 높음 (기준 35)`,
      expectedEffect: `레벨업 필요 EXP 증가. 진행 속도 조절.`,
    });
  }

  // Rule 3: Too slow progression → speed up
  if (m.avgLevel < 5 && m.totalUsers > 5 && m.engagementRate > 0) {
    const newThreshold = Math.max(1.1, config.expThresholdMultiplier - 0.2);
    patches.push({
      patch: { expThresholdMultiplier: newThreshold },
      reason: `평균 레벨 ${m.avgLevel}로 낮음 (기준 5)`,
      expectedEffect: `레벨업 필요 EXP 감소. 초반 진행 속도 향상.`,
    });
  }

  // Rule 4: Evolution balance poor → adjust tier levels
  if (m.balanceScore < 40 && m.totalUsers > 5) {
    const dominated = Object.entries(stats.evolutionDistribution).sort(
      (a, b) => b[1] - a[1]
    );
    if (dominated.length > 0) {
      patches.push({
        patch: {
          evolutionTierLevels: {
            1: TIER_LEVELS[1] + 2,
            2: TIER_LEVELS[2] + 5,
            3: TIER_LEVELS[3],
          },
        },
        reason: `진화 분포 불균형 (밸런스 점수 ${m.balanceScore}/100). 현재 지배적 유형: ${dominated[0][0]}(${dominated[0][1]}명)`,
        expectedEffect: `진화 단계별 필요 레벨 상향. 다양한 진화 유도.`,
      });
    }
  }

  // Rule 5: Guild neglect → buff guild rewards
  if (m.todayFeeds < 5 && m.totalUsers > 10) {
    patches.push({
      patch: { guildExpPerFeed: config.guildExpPerFeed + 3 },
      reason: `길드 활동 저조 — 금일 피드 ${m.todayFeeds}회`,
      expectedEffect: `길드 기여 EXP 증가. 커뮤니티 활동 촉진.`,
    });
  }

  return patches;
}

function generatePatchFile(patches: BalancePatch[]): string {
  const merged = patches.reduce<Partial<GameConfig>>((acc, p) => {
    if (p.patch.evolutionTierLevels && acc.evolutionTierLevels) {
      return { ...acc };
    }
    return { ...acc, ...p.patch };
  }, {});

  const reasons = patches.map((p) => `// ${p.reason}\n// → ${p.expectedEffect}`).join("\n");

  return `// Auto-generated balance patch by Regression Master
// Generated: ${new Date().toISOString()}
// Rules triggered:
${reasons}

export const BALANCE_PATCH = ${JSON.stringify(merged, null, 2)} as const;
`;
}

function generateReport(stats: GameStats, patches: BalancePatch[]): string {
  const m = stats.metrics;

  return `# 🧬 Regression Master Report
**Generated**: ${new Date().toISOString()}

## 📊 Current Metrics
| Metric | Value |
|--------|-------|
| Total Users | ${m.totalUsers} |
| Active Today | ${m.activeToday} |
| Engagement | ${m.engagementRate}% |
| Avg Level | ${m.avgLevel} |
| Balance Score | ${m.balanceScore}/100 |
| Today Feeds | ${m.todayFeeds} |

## 🎯 Evolution Distribution
${Object.entries(stats.evolutionDistribution)
  .map(
    ([type, count]) =>
      `- ${EVOLUTION_TABLE.find((e) => e.id === type)?.emoji || "🟢"} ${type}: ${count}`
  )
  .join("\n")}

## 🔧 Detected Issues
${stats.recommendations.length > 0 ? stats.recommendations.map((r) => `- ⚠️ ${r}`).join("\n") : "- ✅ No issues detected"}

## 📐 Proposed Patches
${patches.length > 0 ? patches.map((p) => `### ${p.reason}\n→ ${p.expectedEffect}`).join("\n\n") : "No patches needed."}

---
*Auto-generated by Regression Master. Review before merging.*
`;
}

async function main() {
  console.log("🧬 Regression Master starting...");
  console.log(`Fetching stats from ${API_STATS_URL}...`);

  const stats = await fetchStats();
  if (!stats) {
    console.error("❌ Cannot fetch stats. Is the server running?");
    process.exit(1);
  }

  console.log("📊 Analyzing balance...");
  const patches = analyzeBalance(stats);

  if (patches.length === 0) {
    console.log("✅ Balance is healthy. No patches needed.");
    process.exit(0);
  }

  console.log(`🔧 ${patches.length} imbalance(s) detected:`);
  for (const p of patches) {
    console.log(`  - ${p.reason}`);
  }

  const patchContent = generatePatchFile(patches);
  const patchPath = join(process.cwd(), ".omo", "balance-patch.ts");
  writeFileSync(patchPath, patchContent);

  const reportContent = generateReport(stats, patches);
  const reportPath = join(process.cwd(), ".omo", "regression-report.md");
  writeFileSync(reportPath, reportContent);

  console.log(`📝 Patch written to ${patchPath}`);
  console.log(`📝 Report written to ${reportPath}`);
  console.log("✅ Regression Master complete.");
}

main().catch((err) => {
  console.error("❌ Regression Master failed:", err);
  process.exit(1);
});
